name: my_melos_workspace
packages:
  - packages/*

sdkPath: .fvm/flutter_sdk


command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  clean_and_bootstrap:
    run: melos clean;
         melos bs 
    description: Clean and Bootstrap all packages.

  build_runner:build:
    run: melos exec --order-dependents --depends-on="build_runner" \ "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run build runner build with order dependents

  test:flutter:
    run: melos exec --dir-exists="test" -c 1 --fail-fast -- "flutter test"
    description: Run Flutter tests for all flutter packages